[package]
authors = ["Maksym Vorobiov <maxim.vorobjov@gmail.com>"]
edition = "2018"
name = "wabench"
version = "0.1.0"

[dependencies]
ndarray-rand = "0.11.0"

[dependencies.ndarray]
version = "0.13.0"
