[package]
authors = ["Maksym Vorobiov <maxim.vorobjov@gmail.com>"]
edition = "2018"
name = "wabench"
version = "0.1.0"

[workspace]
members = ["crates/*"]

[dependencies]
ndarray = "0.13.0"
ndarray-rand = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
instant = { version = "0.1", features = [ "now" ] }

[patch.crates-io]
# yew should be changesd once PR https://github.com/yewstack/yew/pull/721 lands:
# yew = { path = "../../../opensource/yew" }
yew = { git = "https://github.com/dunnock/yew", branch = "extensible-agent" }
wasi-worker-yew = { path="../wasi-worker/crates/wasi-worker-yew" }