[package]
authors = ["Maksym Vorobiov <maxim.vorobjov@gmail.com>"]
edition = "2018"
name = "wabench"
version = "0.1.0"

[dependencies]
ndarray = "0.13.0"
ndarray-rand = "0.11.0"
serde = { version = "1.0", features = ["derive"] }

[dependencies.rand]
features = ["wasm-bindgen"]
