[package]
authors = ["Maksym Vorobiov <maxim.vorobjov@gmail.com>"]
edition = "2018"
name = "wabench-web"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
yew = "0.9.0"
console_error_panic_hook = { version = "0.1.6", optional = true }

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.wabench]
path = ".."

